fix: don't panic when piping
doy/rbw pull request #82
Opened 2022-02-13 20:03 UTC by Witcher01

Piping stdout to something like `head`, which closes rbw's stdout before
it's done writing everything, causes a panic.
The panic is circumvented by using `writeln!` instead of `println!` and
ignoring the error when it's of kind `BrokenPipe`.
Closes #79

2022-05-01 15:12 UTC, svenstaro commented
@doy could you take a look at this?

2022-07-18 16:24 UTC, kpcyrd approved these changes

2022-07-19 04:09 UTC, svenstaro commented
@doy ping

2022-07-19 04:09 UTC, svenstaro requested changes

2022-07-19 04:09 UTC, svenstaro commented on src/bin/rbw/commands.rs
> +        // this happens when piping stdout in a shell
```suggestion
        // Write to stdout but don't panic when pipe gets closed
        // which is what happens when piping stdout in a shell.
```

2023-02-18 19:07 UTC, merged